<a href="https://colab.research.google.com/github/eboekenh/Agentic-AI-Bootcamp/blob/main/3_Answers_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

### **1. Print "+"**

**Description:**
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.
Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

**Examples:**
Input 1:
3
Output 1:

```
[[0 1 0]
 [1 1 1]
 [0 1 0]]
```

Input 2:
5
Output 1:

```
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
```

**Explanation:** Notice that the 1s in the arrays make a shape like '+'.


In [13]:
# Write your code here
n = 5
array_zeros = np.zeros((n,n), dtype = int)




In [ ]:
middle_row = n//2

In [15]:
array_zeros[:,middle_row] = 1
array_zeros

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [16]:
array_zeros[middle_row,:] =1
array_zeros

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

### **2. Weight Loss**

**Description:** With your 25th birthday fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday.

```
import numpy as np

weights = 175 - np.arange(5*7)/5
print(weights)
```

Given these daily weights, build an array with your average weight per weekend.

Example:
```
Week 1 weight = [1, 2, 3, 4, 5, 6, 7]
Week 1 weekend average weight = (6 + 7)/2 = 6.5
```


In [29]:
weights = 175 - np.arange(5*7)/5
print(weights)

[175.  174.8 174.6 174.4 174.2 174.  173.8 173.6 173.4 173.2 173.  172.8
 172.6 172.4 172.2 172.  171.8 171.6 171.4 171.2 171.  170.8 170.6 170.4
 170.2 170.  169.8 169.6 169.4 169.2 169.  168.8 168.6 168.4 168.2]


In [54]:
week_list =[]
for i in range(0,len(weights),7):
  week_list.append(weights[i:i+7])
print(week_list)



[array([175. , 174.8, 174.6, 174.4, 174.2, 174. , 173.8]), array([173.6, 173.4, 173.2, 173. , 172.8, 172.6, 172.4]), array([172.2, 172. , 171.8, 171.6, 171.4, 171.2, 171. ]), array([170.8, 170.6, 170.4, 170.2, 170. , 169.8, 169.6]), array([169.4, 169.2, 169. , 168.8, 168.6, 168.4, 168.2])]


In [61]:
np_weeklist= np.array(week_list)
average_array = []
for i in week_list:
  average_weight = np.average(i[-2:])
  average_array.append(average_weight)
print(average_array)


[np.float64(173.9), np.float64(172.5), np.float64(171.1), np.float64(169.7), np.float64(168.3)]


### **3. Gaming Nicks**

**Description:** You want to start playing a first person shooter game and you are confused to find a gaming nick for yourself, hence you asked your friends and you’ve compiled the names into a Series called nicks.
import numpy as np
import pandas as pd



```
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')
```

Determine how many people voted for the names ‘Phoenix’, ‘roger’, and ‘Pik’.


In [4]:
import pandas as pd

In [5]:
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')

In [14]:
counts = nicks.value_counts()
type(counts)
print(counts["Phoenix"], " people voted Phoenix.")
print(counts["roger"], " people voted roger.")
print(counts["Pik"], " people voted Pik.")

4  people voted Phoenix.
3  people voted roger.
2  people voted Pik.
